spring.application.name=CinemaBh
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# works without this with command line runner
# currently flyway doesn't work without this,
# probably due to the fact that db entity classes are not created yet
# spring.jpa.hibernate.ddl-auto=validate
logging.level.root=debug