spring.application.name=CinemaBh
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true
# default if FRONTEND_URL is not set in environment variables
frontend.url=http://localhost:5173
spring.mvc.validation.fail-fast=false