package com.atlantbh.cinemabh.enums;

public enum AuthEventType {
  LOGIN,
  REGISTER,
  REQUEST_RESET_PASSWORD,
  CONFIRM_PASSWORD_RESET,
  PASSWORD_VALIDATION,
  PHONE_NUMBER_VALIDATION,
  EMAIL_VALIDATION,
  IMAGE_VALIDATION,
  ISSUE_CODE,
  ISSUE_REFRESH_TOKEN,
  REFRESH_TOKEN_VALIDATION,
  ISSUE_ACCESS_TOKEN,
  VALIDATE_CODE,
  VERIFY_ACCOUNT
}
