INSERT INTO personnel (name, type)
VALUES ('Christopher Nolan', 'DIRECTOR'),
       ('Jonathan Nolan', 'WRITER'),
       ('David S. Goyer', 'WRITER'),
       ('Christian Bale', 'CAST'),
       ('Heath Ledger', 'CAST'),
       ('Aaron Eckhart', 'CAST'),
       ('Gary Oldman', 'CAST'),
       ('Michael Caine', 'CAST'),
       ('Morgan Freeman', 'CAST'),
       ('Maggie Gyllenhaal', 'CAST'),
       ('Frank Darabont', 'DIRECTOR'),
       ('Stephen King', 'WRITER'),
       ('Frank Darabont', 'WRITER'),
       ('Tim Robbins', 'CAST'),
       ('Morgan Freeman', 'CAST'),
       ('Bob Gunton', 'CAST'),
       ('Clancy Brown', 'CAST'),
       ('Quentin Tarantino', 'DIRECTOR'),
       ('Quentin Tarantino', 'WRITER'),
       ('Roger Avary', 'WRITER'),
       ('John Travolta', 'CAST'),
       ('Samuel L. Jackson', 'CAST'),
       ('Uma Thurman', 'CAST'),
       ('Bruce Willis', 'CAST'),
       ('David Fincher', 'DIRECTOR'),
       ('Chuck Palahniuk', 'WRITER'),
       ('Jim Uhls', 'WRITER'),
       ('Brad Pitt', 'CAST'),
       ('Edward Norton', 'CAST'),
       ('Helena Bonham Carter', 'CAST'),
       ('Meat Loaf', 'CAST'),
       ('Jared Leto', 'CAST'),
       ('Lana Wachowski', 'DIRECTOR'),
       ('Lilly Wachowski', 'DIRECTOR'),
       ('Lana Wachowski', 'WRITER'),
       ('Lilly Wachowski', 'WRITER'),
       ('Keanu Reeves', 'CAST'),
       ('Laurence Fishburne', 'CAST'),
       ('Carrie-Anne Moss', 'CAST'),
       ('Hugo Weaving', 'CAST'),
       ('Joe Pantoliano', 'CAST'),
       ('Robert Zemeckis', 'DIRECTOR'),
       ('Winston Groom', 'WRITER'),
       ('Eric Roth', 'WRITER'),
       ('Tom Hanks', 'CAST'),
       ('Robin Wright', 'CAST'),
       ('Gary Sinise', 'CAST'),
       ('Sally Field', 'CAST'),
       ('Ridley Scott', 'DIRECTOR'),
       ('Hampton Fancher', 'WRITER'),
       ('David Webb Peoples', 'WRITER'),
       ('Harrison Ford', 'CAST'),
       ('Rutger Hauer', 'CAST'),
       ('Sean Young', 'CAST'),
       ('Daryl Hannah', 'CAST'),
       ('Peter Jackson', 'DIRECTOR'),
       ('Fran Walsh', 'WRITER'),
       ('Philippa Boyens', 'WRITER'),
       ('Peter Jackson', 'WRITER'),
       ('Elijah Wood', 'CAST'),
       ('Ian McKellen', 'CAST'),
       ('Viggo Mortensen', 'CAST'),
       ('Orlando Bloom', 'CAST'),
       ('Sean Astin', 'CAST'),
       ('Andy Serkis', 'CAST'),
       ('Steven Spielberg', 'DIRECTOR'),
       ('Michael Crichton', 'WRITER'),
       ('David Koepp', 'WRITER'),
       ('Sam Neill', 'CAST'),
       ('Laura Dern', 'CAST'),
       ('Jeff Goldblum', 'CAST'),
       ('Richard Attenborough', 'CAST'),
       ('Samuel L. Jackson', 'CAST'),
       ('Martin Scorsese', 'DIRECTOR'),
       ('Nicholas Pileggi', 'WRITER'),
       ('Martin Scorsese', 'WRITER'),
       ('Robert De Niro', 'CAST'),
       ('Ray Liotta', 'CAST'),
       ('Joe Pesci', 'CAST'),
       ('Lorraine Bracco', 'CAST'),
       ('Paul Sorvino', 'CAST');

INSERT INTO movies_personnel (movie_id, personnel_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 8),
       (1, 9),
       (1, 10),
       (2, 11),
       (2, 12),
       (2, 13),
       (2, 14),
       (2, 15),
       (2, 16),
       (2, 17),
       (3, 18),
       (3, 19),
       (3, 20),
       (3, 21),
       (3, 22),
       (3, 23),
       (3, 24),
       (4, 25),
       (4, 26),
       (4, 27),
       (4, 28),
       (4, 29),
       (4, 30),
       (4, 31),
       (4, 32),
       (5, 33),
       (5, 34),
       (5, 35),
       (5, 36),
       (5, 37),
       (5, 38),
       (5, 39),
       (5, 40),
       (5, 41),
       (6, 42),
       (6, 43),
       (6, 44),
       (6, 45),
       (6, 46),
       (6, 47),
       (6, 48),
       (7, 49),
       (7, 50),
       (7, 51),
       (7, 52),
       (7, 53),
       (7, 54),
       (7, 55),
       (8, 56),
       (8, 57),
       (8, 58),
       (8, 59),
       (8, 60),
       (8, 61),
       (8, 62),
       (8, 63),
       (8, 64),
       (9, 65),
       (9, 66),
       (9, 67),
       (9, 68),
       (9, 69),
       (9, 70),
       (9, 71),
       (9, 72),
       (10, 73),
       (10, 74),
       (10, 75),
       (10, 76),
       (10, 77),
       (10, 78),
       (10, 79),
       (10, 80);